### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by brabbitdousha** [lcp29/trimesh-ray-optix#3]
my mesh is updating so I need to call '''RayMeshIntersector''' many times, however, this will cause memory leak, since every time I iterate, memory increases, could you provide a safe way to release memory?

**Comment by brabbitdousha** [comment]
I tried with update_raw, and this problem disappears now.

**Comment by lcp29** [comment]
sorry for late documents

**Comment by lcp29** [comment]
There is a memory leak when the AS Python wrapper gets deleted. I fixed it in abf40bb.

Thanks for your report.

**Comment by brabbitdousha** [comment]
Thanks!
