### ISSUE TITLE
bug in test.py

### ISSUE THREAD

**Issue by eleboss** [lcp29/trimesh-ray-optix#7]
Hi thanks for work.
The demo code contains bugs.

`If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'].
  warnings.warn(
[4][DISKCACHE]: Cache hit for key: ptx-29708-key43edaa26f17bcb053694b44e0bb11e65-sm_89-rtc1-drv560.35.03

[4][COMPILER]: 
[4][COMPILER]: Info: Pipeline statistics
	module(s)                            :     1
	entry function(s)                    :     3
	trace call(s)                        :     1
	continuation callable call(s)        :     0
	direct callable call(s)              :     0
	basic block(s) in entry functions    :     3
	instruction(s) in entry functions    :   106
	non-entry function(s)                :     0
	basic block(s) in non-entry functions:     0
	instruction(s) in non-entry functions:     0
	debug information                    :    no

[4][COMPILER]: Info: Pipeline statistics
	module(s)                            :     1
	entry function(s)                    :     3
	trace call(s)                        :     1
	continuation callable call(s)        :     0
	direct callable call(s)              :     0
	basic block(s) in entry functions    :     3
	instruction(s) in entry functions    :   108
	non-entry function(s)                :     0
	basic block(s) in non-entry functions:     0
	instruction(s) in non-entry functions:     0
	debug information                    :    no

[4][COMPILER]: Info: Pipeline statistics
	module(s)                            :     1
	entry function(s)                    :     3
	trace call(s)                        :     1
	continuation callable call(s)        :     0
	direct callable call(s)              :     0
	basic block(s) in entry functions    :     3
	instruction(s) in entry functions    :   210
	non-entry function(s)                :     0
	basic block(s) in non-entry functions:     0
	instruction(s) in non-entry functions:     0
	debug information                    :    no

[4][COMPILER]: Info: Pipeline statistics
	module(s)                            :     1
	entry function(s)                    :     2
	trace call(s)                        :     1
	continuation callable call(s)        :     0
	direct callable call(s)              :     0
	basic block(s) in entry functions    :     2
	instruction(s) in entry functions    :   101
	non-entry function(s)                :     0
	basic block(s) in non-entry functions:     0
	instruction(s) in non-entry functions:     0
	debug information                    :    no

[4][COMPILER]: Info: Pipeline statistics
	module(s)                            :     1
	entry function(s)                    :     2
	trace call(s)                        :     1
	continuation callable call(s)        :     0
	direct callable call(s)              :     0
	basic block(s) in entry functions    :    12
	instruction(s) in entry functions    :   300
	non-entry function(s)                :     0
	basic block(s) in non-entry functions:     0
	instruction(s) in non-entry functions:     0
	debug information                    :    no

Traceback (most recent call last):
  File "/home/eleboss/Documents/trimesh-ray-optix/test/test.py", line 11, in <module>
    r = RayMeshIntersector(m)
TypeError: RayMeshIntersector.__init__() takes 1 positional argument but 2 were given
`

**Comment by eleboss** [comment]
solution
use
intersector = RayMeshIntersector(**mesh**=mesh)

**Comment by lcp29** [comment]
Thank you so much for the report! I have fixed it in test.py!
