### ISSUE TITLE
error on multiple GPUs machine, when loading large mesh file.

### ISSUE THREAD

**Issue by eleboss** [lcp29/trimesh-ray-optix#8]
Dear team, 
Thanks for the code. 
I used it a lot for my project. I have no problem using CUDA12.4+560+optix8.0 in a single card 4080 PC. But when transferring the same code to the server with an identical setup (CUDA12.4+560+optix8.0), I cannot  load a very large mesh , due to the memory error stated below:
`
error (/ghome/h2/anaconda3/envs/hloc/lib/python3.10/site-packages/triro/backend/ray.cpp: line 85): an illegal memory access was encountered
`
Do you have any ideas how to resolve that?

**Comment by lcp29** [comment]
Thank for your support!
Is the mesh with the similar size loadable locally?

**Comment by eleboss** [comment]
Yep the mesh is loadable , the strange thing is I try the update_raw, it works well and is fully loaded. 

So I am wondering now, are there some sync problems when loading large meshes, do we need to wait till the mesh is constructed?

**Comment by eleboss** [comment]
BTW, the 4 gpus server using 4090*4 with 24GBs, so I think it should be OK to load.

**Comment by eleboss** [comment]
I know why, I am using half to load the large mesh, so jumps memory error.

**Comment by lcp29** [comment]
Thank you for the report. I'll try to support half precision.
